name: straditize_docs
channels:
    - chilipp/label/dev
    - chilipp/label/master
    - chilipp
dependencies:
    - python=3.7
    - psyplot-gui>=1.2.0
    - pygments
    - sphinx!=1.7.5
    - psy-simple>=1.2.0
    - psyplot>=1.2.0
    - netcdf4
    - openpyxl
    - scikit-image
    - scipy
    - psy-strat
    - pip:
        - autodocsumm
        - sphinx-argparse
        - sphinx-nbexamples
